version: '3.9'

services:

  composer:
    image: composer:1.9.3
    working_dir: /ver/www/html
    volumes:
      - ./:/ver/www/html
    command: composer install
      
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    ports:
      - $DB_PORT:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5m

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MA_USER: $DB_USERNAME
      PMA_PASSWORD: $DB_PASSWORD
    ports:
      - 8080:80

  php:
    depends_on:
      composer:
        condition: service_completed_successfully
      mysql:
        condition: service_healthy
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      
  nginx:
    depends_on:
      - php
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

volumes:
  db-data:
